#!/usr/bin/env python3
"""Generate the v1 OTLP fast OTLP encoder pieces from a checked-in spec.

This generator is intentionally narrow. It emits only the row-level OTLP
projection code plus optional full-batch envelope helpers, and still relies on
shared handwritten wire primitives.
"""

from __future__ import annotations

import json
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SPEC = REPO / "crates" / "logfwd-output" / "codegen" / "otlp_log_record_fast_v1.schema.json"
OUT = REPO / "crates" / "logfwd-output" / "src" / "generated" / "otlp_log_record_fast_v1.rs"


def load_spec() -> dict:
    return json.loads(SPEC.read_text())


def render(spec: dict) -> str:
    roles = spec["roles"]
    order = ", ".join(f'"{role["name"]}"' for role in roles)
    emit = spec.get("emit", {})
    emit_row_encoder = bool(emit.get("row_encoder", True))
    emit_batch_envelope = bool(emit.get("batch_envelope", False))
    batch_encoder = ""
    if emit_batch_envelope:
        batch_encoder = """

/// Generated v1 OTLP full-batch encoder with specialized envelope/framing emission.
pub(super) fn encode_batch_generated_fast_v1(
    columns: &BatchColumns<'_>,
    metadata: &BatchMetadata,
    num_rows: usize,
    buf: &mut Vec<u8>,
) {
    let instrumentation_scope_inner_size =
        bytes_field_size(otlp::INSTRUMENTATION_SCOPE_NAME, SCOPE_NAME.len())
            + bytes_field_size(otlp::INSTRUMENTATION_SCOPE_VERSION, SCOPE_VERSION.len());

    let mut resource_msg: Vec<u8> = Vec::new();
    if !metadata.resource_attrs.is_empty() {
        for (k, v) in metadata.resource_attrs.as_ref() {
            encode_key_value_string(
                &mut resource_msg,
                otlp::RESOURCE_ATTRIBUTES,
                k.as_bytes(),
                v.as_bytes(),
            );
        }
    }

    let mut records_buf: Vec<u8> = Vec::with_capacity(num_rows * 128);
    let mut record_lens: Vec<usize> = Vec::with_capacity(num_rows);
    let mut scope_logs_inner_size =
        bytes_field_size(otlp::SCOPE_LOGS_SCOPE, instrumentation_scope_inner_size);

    for row in 0..num_rows {
        let start = records_buf.len();
        encode_row_as_log_record_fast_v1(columns, row, metadata, &mut records_buf);
        let record_len = records_buf.len() - start;
        record_lens.push(record_len);
        scope_logs_inner_size += 1 + varint_len(record_len as u64) + record_len;
    }

    let mut resource_inner_size =
        bytes_field_size(otlp::RESOURCE_LOGS_SCOPE_LOGS, scope_logs_inner_size);
    if !resource_msg.is_empty() {
        resource_inner_size += bytes_field_size(otlp::RESOURCE_LOGS_RESOURCE, resource_msg.len());
    }
    let request_size =
        bytes_field_size(otlp::EXPORT_LOGS_REQUEST_RESOURCE_LOGS, resource_inner_size);

    buf.clear();
    buf.reserve(request_size);

    encode_tag(
        buf,
        otlp::EXPORT_LOGS_REQUEST_RESOURCE_LOGS,
        otlp::WIRE_TYPE_LEN,
    );
    encode_varint(buf, resource_inner_size as u64);

    if !resource_msg.is_empty() {
        encode_bytes_field(buf, otlp::RESOURCE_LOGS_RESOURCE, &resource_msg);
    }

    encode_tag(buf, otlp::RESOURCE_LOGS_SCOPE_LOGS, otlp::WIRE_TYPE_LEN);
    encode_varint(buf, scope_logs_inner_size as u64);

    encode_tag(buf, otlp::SCOPE_LOGS_SCOPE, otlp::WIRE_TYPE_LEN);
    encode_varint(buf, instrumentation_scope_inner_size as u64);
    encode_bytes_field(buf, otlp::INSTRUMENTATION_SCOPE_NAME, SCOPE_NAME);
    encode_bytes_field(buf, otlp::INSTRUMENTATION_SCOPE_VERSION, SCOPE_VERSION);

    let scope_logs_record_tag =
        ((otlp::SCOPE_LOGS_LOG_RECORDS << 3) | u32::from(otlp::WIRE_TYPE_LEN)) as u8;
    let mut cursor = 0usize;
    for record_len in record_lens {
        buf.push(scope_logs_record_tag);
        encode_varint(buf, record_len as u64);
        let end = cursor + record_len;
        buf.extend_from_slice(&records_buf[cursor..end]);
        cursor = end;
    }
}
"""
    return f"""// @generated by scripts/generate_otlp_fast_encoder.py; DO NOT EDIT.
// spec: {spec["name"]} v{spec["version"]}
// column order: {order}
// emit.row_encoder={str(emit_row_encoder).lower()}
// emit.batch_envelope={str(emit_batch_envelope).lower()}

use arrow::array::Array;
use super::{{AttrArray, BatchColumns, BatchMetadata, encode_fixed32, encode_key_value_bool,
    encode_key_value_double, encode_key_value_int, encode_key_value_string, encode_tag,
    encode_varint, str_value, SCOPE_NAME, SCOPE_VERSION}};
use logfwd_core::otlp::{{self, Severity, bytes_field_size, encode_bytes_field, encode_fixed64,
    encode_varint_field, hex_decode, parse_severity, parse_timestamp_nanos, varint_len}};

/// Generated v1 OTLP LogRecord encoder.
pub(super) fn encode_row_as_log_record_fast_v1(
    columns: &BatchColumns<'_>,
    row: usize,
    metadata: &BatchMetadata,
    buf: &mut Vec<u8>,
) {{
    let timestamp_ns: u64 = if let Some((_, arr)) = columns.timestamp_col.as_ref() {{
        if arr.is_null(row) {{
            0
        }} else {{
            parse_timestamp_nanos(arr.value(row).as_bytes()).unwrap_or(0)
        }}
    }} else {{
        0
    }};

    let (severity_num, severity_text): (Severity, &[u8]) =
        if let Some((_, arr)) = columns.level_col.as_ref() {{
            if arr.is_null(row) {{
                (Severity::Unspecified, b"")
            }} else {{
                parse_severity(arr.value(row).as_bytes())
            }}
        }} else {{
            (Severity::Unspecified, b"")
        }};

    let body: &str = match (columns.body_col.as_ref(), columns.raw_col.as_ref()) {{
        (Some((_, body)), _) if !body.is_null(row) => body.value(row),
        (_, Some((_, raw))) if !raw.is_null(row) => raw.value(row),
        _ => "",
    }};
    let body_bytes = body.as_bytes();

    if timestamp_ns > 0 {{
        encode_fixed64(buf, otlp::LOG_RECORD_TIME_UNIX_NANO, timestamp_ns);
    }}

    if severity_num as u8 > 0 {{
        encode_varint_field(buf, otlp::LOG_RECORD_SEVERITY_NUMBER, severity_num as u64);
    }}

    if !severity_text.is_empty() {{
        encode_bytes_field(buf, otlp::LOG_RECORD_SEVERITY_TEXT, severity_text);
    }}

    if !body_bytes.is_empty() {{
        let anyvalue_inner_size = bytes_field_size(otlp::ANY_VALUE_STRING_VALUE, body_bytes.len());
        encode_tag(buf, otlp::LOG_RECORD_BODY, otlp::WIRE_TYPE_LEN);
        encode_varint(buf, anyvalue_inner_size as u64);
        encode_bytes_field(buf, otlp::ANY_VALUE_STRING_VALUE, body_bytes);
    }}

    for (field_name, attr) in &columns.attribute_cols {{
        match attr {{
            AttrArray::Int(arr) => {{
                if !arr.is_null(row) {{
                    encode_key_value_int(
                        buf,
                        otlp::LOG_RECORD_ATTRIBUTES,
                        field_name.as_bytes(),
                        arr.value(row),
                    );
                }}
            }}
            AttrArray::Float(arr) => {{
                if !arr.is_null(row) {{
                    encode_key_value_double(
                        buf,
                        otlp::LOG_RECORD_ATTRIBUTES,
                        field_name.as_bytes(),
                        arr.value(row),
                    );
                }}
            }}
            AttrArray::Bool(arr) => {{
                if !arr.is_null(row) {{
                    encode_key_value_bool(
                        buf,
                        otlp::LOG_RECORD_ATTRIBUTES,
                        field_name.as_bytes(),
                        arr.value(row),
                    );
                }}
            }}
            AttrArray::Str(arr) => {{
                if !arr.is_null(row) {{
                    encode_key_value_string(
                        buf,
                        otlp::LOG_RECORD_ATTRIBUTES,
                        field_name.as_bytes(),
                        arr.value(row).as_bytes(),
                    );
                }}
            }}
            AttrArray::OtherStr(arr) => {{
                if !arr.is_null(row) {{
                    encode_key_value_string(
                        buf,
                        otlp::LOG_RECORD_ATTRIBUTES,
                        field_name.as_bytes(),
                        str_value(*arr, row).as_bytes(),
                    );
                }}
            }}
        }}
    }}

    if let Some((_, arr)) = columns.flags_col {{
        if !arr.is_null(row) {{
            let raw = arr.value(row);
            if let Ok(flags) = u32::try_from(raw) {{
                encode_fixed32(buf, otlp::LOG_RECORD_FLAGS, flags);
            }}
        }}
    }}

    if let Some((_, arr)) = columns.trace_id_col.as_ref() {{
        if !arr.is_null(row) {{
            let hex = arr.value(row);
            let mut decoded = [0u8; 16];
            if hex_decode(hex.as_bytes(), &mut decoded) {{
                encode_bytes_field(buf, otlp::LOG_RECORD_TRACE_ID, &decoded);
            }}
        }}
    }}

    if let Some((_, arr)) = columns.span_id_col.as_ref() {{
        if !arr.is_null(row) {{
            let hex = arr.value(row);
            let mut decoded = [0u8; 8];
            if hex_decode(hex.as_bytes(), &mut decoded) {{
                encode_bytes_field(buf, otlp::LOG_RECORD_SPAN_ID, &decoded);
            }}
        }}
    }}

    encode_fixed64(
        buf,
        otlp::LOG_RECORD_OBSERVED_TIME_UNIX_NANO,
        metadata.observed_time_ns,
    );
}}
{batch_encoder}
"""


def main() -> None:
    spec = load_spec()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(spec))


if __name__ == "__main__":
    main()
